resultCode
결과코드
resultMsg
결과메시지
numOfRows
한 페이지 결과 수
pageNo
페이지번호
totalCount
전체 결과 수
SEQ
게시글번호(감염현황 고유값)
STATE_DT
기준일
STATE_TIME
기준시간
DECIDE_CNT
확진자 수
CLEAR_CNT
격리해제 수
검사진행 수
EXAM_CNT
검사진행 수
사망자 수
DEATH_CNT
사망자 수
치료중 환자 수
CARE_CNT
치료중 환자 수
결과 음성 수
RESUTL_NEG_CNT
결과 음성 수
누적 검사 수
ACC_EXAM_CNT
누적 검사 수
누적 검사 완료 수
ACC_EXAM_COMP_CNT
누적 검사 완료 수
누적 확진률
ACC_DEF_RATE
누적 확진률
등록일시분초
CREATE_DT
등록일시분초
수정일시분초
UPDATE_DT
수정일시분초

In [1]:
import requests
import xml.etree.ElementTree as ET
import pandas as pd

In [2]:
url ='http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19InfStateJson?serviceKey=WRvGBkn9UEtw%2BAsg0tYo210Etxvb1QEcAX%2BwfWvOxVGYJkh1CNZ%2FY4QFa0r7j4bhT4NjPu7z1i1ck8ZgsKMt2Q%3D%3D&pageNo=1&numOfRows=10&startCreateDt=20210310&endCreateDt=20210515'

In [11]:
r = requests.get(url)
root = ET.fromstring(r.text)
items = root.iter(tag = 'item')

In [14]:
total = []
for element in items:
    tmp_dict = dict()
    for x in element:
        tmp_dict[x.tag] = x.text
    total.append(tmp_dict)

In [16]:
df = pd.DataFrame(total)

In [17]:
df

,accDefRate,accExamCnt,accExamCompCnt,careCnt,clearCnt,createDt,deathCnt,decideCnt,examCnt,resutlNegCnt,seq,stateDt,stateTime,updateDt
0,1.416158717,9241152,9153635,7847,119892,2021-05-13 00:00:00.000,1891,129630,87517,9024005,480,20210513,00:00,2021-10-07 10:30:51.51
1,1.413966632,9201538,9117259,7671,119360,2021-05-12 00:00:00.000,1884,128915,84279,8988344,479,20210512,00:00,2021-10-07 10:30:51.51
2,1.412840025,9164283,9079655,7696,118706,2021-05-11 00:00:00.000,1879,128281,84628,8951374,478,20210511,00:00,2021-10-07 10:30:51.51
3,1.413605557,9122058,9038660,8064,117832,2021-05-10 00:00:00.000,1875,127771,83398,8910889,477,20210510,00:00,2021-10-07 10:30:51.51
4,1.410694676,9105770,9024490,8023,117411,2021-05-09 00:00:00.000,1874,127308,81280,8897182,476,20210509,00:00,2021-10-07 10:30:51.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,1.366772257,7066400,6996557,6565,87393,2021-03-14 00:00:00.000,1669,95627,69843,6900930,420,20210314,00:00,2021-10-07 10:30:51.51
61,1.36365193,7046781,6978907,6888,86613,2021-03-13 00:00:00.000,1667,95168,67874,6883739,419,20210313,00:00,2021-10-07 10:30:51.51
62,1.363465187,7012663,6943925,7284,85732,2021-03-12 00:00:00.000,1662,94678,68738,6849247,418,20210312,00:00,2021-10-07 10:30:51.51
63,1.363346349,6976984,6908736,7873,84665,2021-03-11 00:00:00.000,1652,94190,68248,6814546,417,20210311,00:00,2021-10-07 10:30:51.51
64,1.364541999,6938883,6868605,7776,84301,2021-03-10 00:00:00.000,1648,93725,70278,6774880,416,20210310,00:00,2021-10-07 10:30:51.51

In [23]:
df["createDt"] = pd.to_datetime(df["createDt"])

In [22]:
df.dtypes

accDefRate                object
accExamCnt                object
accExamCompCnt            object
careCnt                   object
clearCnt                  object
createDt          datetime64[ns]
deathCnt                  object
decideCnt                 object
examCnt                   object
resutlNegCnt              object
seq                       object
stateDt                   object
stateTime                 object
updateDt                  object
dtype: object